### ISSUE TITLE
Discuss the best way to store direct upload posts in the Database

### ISSUE THREAD

**Issue by SlidewhistleIncognito** [shareOfTheMind/TelegramBot#11]

**Comment by SlidewhistleIncognito** [comment]
Currently, the direct upload posts are being stored as such

Post(poster=message.chat.username, likes=0, views=0, source="direct", share_link=photo_media.file_id, file_type=None, submitter=submitter)

where the poster is the sender off the message, and the sharelink is the file_id used to store the data on tgram buckets. I want to think about whether we should pull down the file and store it in the s3 ourselves or not.

**Comment by gabealoi** [comment]
> Currently, the direct upload posts are being stored as such
> 
> Post(poster=message.chat.username, likes=0, views=0, source="direct", share_link=photo_media.file_id, file_type=None, submitter=submitter)
> 
> where the poster is the sender off the message, and the sharelink is the file_id used to store the data on tgram buckets. I want to think about whether we should pull down the file and store it in the s3 ourselves or not.

I think it comes down to whether or not we want to store the media in our buckets or build a relation to Telegram's datastore to pull data from the feed. I think we'll start storing in our s3, but if we want to backfill we'll have to read in all of the media we do have--_which may not have the metadata we need associated with them. _
